---
title: "Overview of 22 Public Utility Companies in the USA"
author: "Harsh Sharma"
output: 
  html_document:
    keep_md: true
---
```{r Loading Packages if required}
knitr::opts_chunk$set(echo = TRUE)
if(!require("pacman")) install.packages("pacman")
pacman::p_load(knitr, rmarkdown, gplots, GGally, mosaic,
               scales, mosaic, mapproj, mlbench, data.table)
search()
theme_set(theme_classic())
```


```{r warning= FALSE}
##Read CSV File
library("data.table")
Utilities.df <- read.csv("Utilities.csv")
```

```{r Datatable}
##Setting Data table
Utilities.dt <- setDT(Utilities.df)
Utilities.dt
```
##Answer 1
```{r Fixed_Variable}
##Fixed Variable
Utilities.dt[, .(minimum=min(Fixed_charge), maximum=max(Fixed_charge),mean=mean(Fixed_charge),
               median=median(Fixed_charge),sd=sd(Fixed_charge))]
```

```{r RoR}
##RoR
Utilities.dt[, .(minimum=min(RoR), maximum=max(RoR),mean=mean(RoR),
                 median=median(RoR),sd=sd(RoR))]
```
```{r Cost}
##Cost
Utilities.dt[, .(minimum=min(Cost), maximum=max(Cost),mean=mean(Cost),
                 median=median(Cost),sd=sd(Cost))]
```
```{r Load_Factor}
##Load Factor
Utilities.dt[, .(minimum=min(Load_factor), maximum=max(Load_factor),mean=mean(Load_factor),
                 median=median(Load_factor),sd=sd(Load_factor))]
```
```{r Demand Growth}
##Demand Growth
Utilities.dt[, .(minimum=min(Demand_growth), maximum=max(Demand_growth),mean=mean(Demand_growth),
                 median=median(Demand_growth),sd=sd(Demand_growth))]
```
```{r Sales }
##Sales
Utilities.dt[, .(minimum=min(Sales), maximum=max(Sales),mean=mean(Sales),
                 median=median(Sales),sd=sd(Sales))]
```
```{r Nuclear}
##Nuclear
Utilities.dt[, .(minimum=min(Nuclear), maximum=max(Nuclear),mean=mean(Nuclear),
                 median=median(Nuclear),sd=sd(Nuclear))]
```
```{r Fuel Cost}
##Fuel Cost
Utilities.dt[, .(minimum=min(Fuel_Cost), maximum=max(Fuel_Cost),mean=mean(Fuel_Cost),
                 median=median(Fuel_Cost),sd=sd(Fuel_Cost))]
```
```{r Interpretation}
##Interpretation:
##We can use standard deviation as the measure of variability. 
##From the output when we compare all the standard deviations of variables, 
##we can observe that sales have the highest variability as its standard deviation is high.
```
##Answer 2
```{r Fixed Charge}
ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$Fixed_charge), 
               fill = "gold1", outlier.color = "firebrick2") + 
   ylab("Fixed charge covering ratio (income/debt)") + 
  ggtitle("Fixed Energy charge Ratio of 22 Companies")
```
```{r }
#RoR

ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$RoR), 
               fill = "gold1", outlier.color = "firebrick2") + 
  ylab("Rate of return on capital") +
  ggtitle("Rate of return on capital of 22 Companies")
```
```{r}
#Cost
ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$Cost), 
               fill = "gold1", outlier.color = "firebrick2") + 
  ylab("Cost per kilowatt capacity in place") + ggtitle("Cost of 22 companies")
```
```{r}
#Load Factor
ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$Load_factor), 
               fill = "gold1", outlier.color = "firebrick2") + 
    ylab("Anuual Load Factor") + ggtitle("Load Factor for 22 Companies")
```
```{r}
#Demand Growth
ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$Demand_growth), 
               fill = "gold1", outlier.color = "firebrick2") + 
    ylab("Peak Kilowatthour Demand Growth") +
  ggtitle("Demand Growth for 22 companies")

```
```{r}
#Sales

ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$Sales), 
               fill = "gold1", outlier.color = "firebrick2") + 
  ylab("sales(kilowatthour use per year)") + ggtitle("Sales for 22 companies")
```
```{r}
#Nuclear

ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$Nuclear), 
               fill = "gold1", outlier.color = "firebrick2") + 
   ylab("Percent Nuclear") + ggtitle("Percent Nuclear for 22 companies")

```
```{r}
#Fuel_Cost

ggplot(Utilities.dt) +
  geom_boxplot(aes(y = Utilities.dt$Fuel_Cost), 
               fill = "gold1", outlier.color = "firebrick2") + 
  xlab("Count") + ylab("Total Fuel Cost(cents per Kilowatthour)") +
  ggtitle("Fuel Cost of 22 companies") 
```
```{r}
##Interpretation:
##There are 8 variables in the data set out of which 2 variables have the outliers.
##Fixed charge and Sales are having extreme values(outliers).
##Fixed charge has totally 4 outliers. The outliers are on the both sides of the box plot.
##Sales has 2 outliers above the box plot
##Statistically any value (X) which satisfies the below equations is called outlier. 
##X < Q1 - 1.5 IQR or X > Q3 + 1.5 IQR where IQR is the difference between the 75th and 
##25th percentiles.
```
##Answer 3
```{r}
##heatmap using ggplot
library(reshape)
cor.mat <- round(cor(Utilities.dt[,!c("Company")]),2)
# rounded correlation matrix
melted.cor.mat <- melt(cor.mat)
ggplot(melted.cor.mat, aes(x = X1, y = X2, fill = value)) +
  scale_fill_gradient2( low = muted("yellow"), mid = "white",
                        high = muted("blue"), midpoint = 0, space = "Lab",
                        na.value = "grey50", guide = "colourbar", aesthetics = "fill") +
  geom_tile() +  
geom_text(aes(x = X1, y = X2, label = value)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Correlation b/w variables of 22 companies")
```
```{r}
##Interpretation:
##From the heat map it is observed that ROR and Fixed Charge are highly positively 
##Correlated variables 
##which means increase in one variable increases the other.
##Sales and Fuel Cost are highly negatively 
##correlated which means decrease in one variable increase the other variable and vice versa.
##We can see that there are many values between 
##-0.1 to 0.1 (For example: -0.01, 0.01, 0.03). 
##This shows that there is no relationship or
##very weak relationship between the variables. 
##Those variables are independent of each other and not related. 
```
##Answer 4
```{r}
## Principal component analysis using unscaled numeric variables in the dataset
pca_unscaled <- prcomp(na.omit(Utilities.dt[,-c(1:1)]))
summary(pca_unscaled)
pca_unscaled$rot
```
```{r}
##Interpretation:
##From the generated values we can see that PC1 has 99.98% of variance which means that the data is 
##mostly dependent on PC1.
##PC1 and PC2 has almost 100% of variance where 
##PC1 accounting for the major variance in data.
##The other variables have 0 variance.
##Hence the primary focus should be on PC1.
```
##Answer 5
```{r}
#principal component analysis using scaled numeric variables
pcs.scaled <- prcomp(na.omit(Utilities.dt[,-c(1:1)]), scale. = T)
summary(pcs.scaled)
pcs.scaled$rot
```
```{r}
##Interpretation:
##After scaling we can observe that there is a difference in proportion of variance 
##among the components.
##Now the variables look distributed and each variable ##have significant impact on the data.
##Now we can’t primarily focus on PC1, we have to consider other PCs as well.Hence dependencies 
##of variables have become wide and accurate.
##The standard deviation has been changed from 
##3549.9901 to 1.4741
##Scaling helps us to standardize the input data.
```





